### ISSUE TITLE
ydlidar_ros2_driver fails to compile on Ubuntu 24.04 / Jazzy on both x86 and rpi

### ISSUE THREAD

**Issue by dmeziere** [linorobot/linorobot2#222]
ydlidar_ros2_driver fails to compile on Ubuntu 24.04 / ROS Jazzy, on both x86 and rpi producing this output :
```
/home/dmeziere/mecanum-1/src/ydlidar_ros2_driver/src/ydlidar_ros2_driver_node.cpp: In function ‘int main(int, char**)’:
/home/dmeziere/mecanum-1/src/ydlidar_ros2_driver/src/ydlidar_ros2_driver_node.cpp:44:26: error: no matching function for call to ‘rclcpp::Node::declare_parameter(const char [5])’
```

Maybe a hint (i am not really into C++ dev) :
```
candidate expects 4 arguments, 1 provided
```

**Comment by PaulBouchier** [comment]
Thanks for the bug report @dmeziere. I've duplicated it. The fix for you is quite simple:

From your workspace (e.g. linorobot2_ws):
```
cd src/ydlidar_ros2_driver
git fetch origin pull/66/head:jazzy
git checkout jazzy
cd ../..
colcon build
```
Now it will compile. Let me know if you still have problems, or close this issue if it fixes it.

The specific error you ran into is caused by an API change in Jazzy. The behavior of declare_parameter has stricter enforcement in ROS 2 Jazzy due to the full rollout of Statically Typed Parameters. Unfortunately, after fixing that problem, there are more Jazzy-related issues behind it. Pull request #66 in the upstream repo (owned by YDLicar) fixes all the problems. If you follow the instructions above it should build.

@grassjelly please advise - you've probably run into this situation before. I've sent a message to YDLidar via their website asking for PR #66 to be merged, but until and unless they merge, the linorobot2 build will be broken. I can imagine several options:
1. We could document the build failure in the installation instructions
2. We could fork their repo and apply PR #66 there, but that leads to all kinds of maintenance issues if people fork our repo then we remove it if YDLidar fixes theirs.

What do you think we should do?

Separately, we should probably build all those lidar drivers in our weekly tests.

**Comment by dmeziere** [comment]
Thank you Paul for the solution, and these explanations are appreciated too. I still have a warning on both architectures but i'm sure it won't make any trouble.
